services:
  # PostgreSQL database for Synapse
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port for external access
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    restart: unless-stopped

  # Matrix Synapse homeserver
  synapse:
    build:
      context: ./synapse
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
      - "8448:8448"
      - "9000:9000"  # Additional port for metrics/debugging
    volumes:
      - ./synapse/data:/data
      - ./synapse/homeserver.yaml:/data/homeserver.yaml:ro
      - ./synapse/log.config:/data/log.config:ro
      - ./synapse/ai-bot-registration.yaml:/data/ai-bot-registration.yaml:ro
      - ./synapse/whatsapp-bridge-registration.yaml:/data/whatsapp-bridge-registration.yaml:ro
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=no
    depends_on:
      - postgres
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    restart: unless-stopped

  # Web client (React)
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_MATRIX_SERVER_URL=http://localhost:8008
    depends_on:
      - synapse
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    restart: unless-stopped

  # AI Bot
  ai-bot:
    build:
      context: ./ai-bot
      dockerfile: Dockerfile
    environment:
      - MATRIX_SERVER_URL=http://synapse:8008
      - MATRIX_USERNAME=@aibot:localhost
      - MATRIX_PASSWORD=aibot_password
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    depends_on:
      - synapse
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    # Enable access to external APIs and host network resources
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    volumes:
      - ./ai-bot/config:/app/config
  

  # Redis for caching (optional but recommended)
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Expose Redis port for external access
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    restart: unless-stopped

  # Document Uploader
  document-uploader:
    build:
      context: ./document-uploader
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MATRIX_SERVER_URL=http://synapse:8008
      - MATRIX_USERNAME=@aibot:localhost
      - MATRIX_PASSWORD=aibot_password
    depends_on:
      - synapse
      - ai-bot
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    volumes:
      - ./document-uploader/uploads:/app/uploads
    restart: unless-stopped

  # WhatsApp Bridge
  whatsapp-bridge:
    build:
      context: ./whatsapp-bridge
      dockerfile: Dockerfile
    ports:
      - "29318:29318"
    environment:
      - MATRIX_SERVER_URL=http://synapse:8008
    depends_on:
      - synapse
      - postgres
    networks:
      - matrix_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host services
    volumes:
      - whatsapp_data:/data
      - ./whatsapp-bridge/config.yaml:/data/config.yaml:ro
      - ./whatsapp-bridge/registration.yaml:/data/registration.yaml:ro
    restart: unless-stopped
  
volumes:
  postgres_data:
  redis_data:
  whatsapp_data:

networks:
  matrix_network:
    driver: bridge
    # Enable external connectivity
    external: false
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1